### PR TITLE
[DROOLS-936] clean-up deps to avoid duplicated classes

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
@pefernan could you please take a look?

**Comment by pefernan** [comment]
@psiroky looks good to me. BTW did you tried to run the showcase? I'm getting a WELD error don't know if related to this change.

**Comment by psiroky** [comment]
@pefernan I did not. I am afraid I can not possibly run all the showcases :( I would not be surprised if the error was there even before this change, but I can take a quick look.

**Comment by pefernan** [comment]
@psiroky I'm going to check master. I'll let you know

**Comment by psiroky** [comment]
I am getting the following which seems to be related to the new Library stuff?
```
"WFLYCTL0080: Failed services" : 
{"jboss.deployment.unit.\"ROOT.war\".WeldStartService" : "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"ROOT.war\".WeldStartService: Failed to start service\n 
Caused by: org.jboss.weld.exceptions.DeploymentException: 
WELD-001408: Unsatisfied dependencies for type ExamplesService with qualifiers @Default\n at injection point [BackedAnnotatedParameter] Parameter 9 of [BackedAnnotatedConstructor] @Inject public
 org.kie.workbench.common.screens.impl.LibraryServiceImpl(OrganizationalUnitService, RepositoryService, KieProjectService, LibraryPreferences, AuthorizationManager, SessionInfo, ExplorerServiceHelper, KieProjectService, ExamplesService, @Named IOService)\n at org.kie.workbench.common.screens.impl.LibraryServiceImpl.<init>(LibraryServiceImpl.java:0)\n"}}, "rolled-back" : true }
```

**Comment by pefernan** [comment]
@psiroky yes that's it. I think I have it fixed. A missing dep. I'll send a PR soon

**Comment by pefernan** [comment]
@psiroky https://github.com/droolsjbpm/jbpm-form-modeler/pull/89

**Comment by psiroky** [comment]
jenkins retest this

**Pull request merged**
