### PR TITLE
GUVNOR-2173 - Asset Oracle: Change Impact prediction

### PR DESCRIPTION
**Pull request by mrietveld**
Change Impact, Part I: building a reference infrastructure that we can query.

For an explanation, see https://github.com/droolsjbpm/kie-wb-common/pull/414

PR set:
- https://github.com/uberfire/uberfire/pull/455
- https://github.com/droolsjbpm/kie-wb-common/pull/414
- https://github.com/droolsjbpm/drools-wb/pull/257
- https://github.com/droolsjbpm/jbpm-designer/pull/375
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/63

### CODE REVIEW

**Comment by mrietveld** [comment]
@pefernan Would you mind reviewing this? Thanks! It will help to read https://github.com/droolsjbpm/kie-wb-common/pull/414 first.

**Comment by mrietveld** [comment]
@psiroky Sorry to bother you again. 

The build failed because of `No space left on device`

```
03:32:12 /home/jenkins/workspace/jbpm-form-modeler-pullrequests/upstream-repos/errai/errai-demos/errai-security-demo/src/main/java/org/jboss/errai/security/demo/server/ServiceImpl.java:[35,7] error: error while writing ServiceImpl: /home/jenkins/workspace/jbpm-form-modeler-pullrequests/upstream-repos/errai/errai-demos/errai-security-demo/src/main/webapp/WEB-INF/classes/org/jboss/errai/security/demo/server/ServiceImpl.class (No space left on device)
```

**Comment by mrietveld** [comment]
jenkins please retest

**Comment by pefernan** [comment]
+1 
@mrietveld thanks!

**Comment by mrietveld** [comment]
jenkins please retest

**Pull request merged**
