### PR TITLE
GUVNOR-2278: Added missing dependencies

### PR DESCRIPTION
**Pull request by pefernan**
Added dependencies due this commit: https://github.com/droolsjbpm/kie-wb-common/commit/9f52d009c42860e2c0f60da9f67022ff2a7819a4

### CODE REVIEW

**Comment by pefernan** [comment]
@psiroky looking at the kie-wb-webap's pom.xml it doesn't has a dependency to kie-wb-decorated-grid-widget module. Maybe it isn't needed, it's only required on the compileSourcesArtifacts. I'll try it and push it again.

**Comment by psiroky** [comment]
Yeah, kie-wb-webapp build is failing as well, because it is missing that dependency.

I've used the provided scope here https://github.com/droolsjbpm/jbpm-designer/pull/103 and it seems to work.

**Comment by pefernan** [comment]
@psiroky changed scope

**Comment by psiroky** [comment]
+1. Merged into master. Thanks @pefernan.

**Pull request merged**
