### PR TITLE
showcase: use shared GWT props + tweak resource config

### PR DESCRIPTION
**Pull request by psiroky**
@pefernan could you please take a look? I've tested this locally and everything seems to work.

### CODE REVIEW

**Comment by porcelli** [comment]
+1

**Comment by pefernan** [comment]
@psiroky +1

**Comment by psiroky** [comment]
We should wait with this one as it currently break integration with IDEA as found by @manstis and @Rikkola. Will keep you posted.

**Comment by psiroky** [comment]
I fixed the SDM in IDEA similarly as in guvnor and drools-wb repos - the showcase now contains only single GWT module, no FastCompiled thing anymore. This should make the maintenance easier. You will need to update your configs if you use `FastCompiled*` somewhere (like the IDEA GWT launcher).

**Comment by csadilek** [comment]
Thanks.

master: 94fd4ae107cf9cc6a3a667d207e06243af7a9f1e

**Pull request closed without merging**
