### PR TITLE
[6.5.x] RHBPMS-5099: Date selector popup not showing up in sub-form

### PR DESCRIPTION
**Pull request by pefernan**
@jsoltes 
Could you please take a look?

### CODE REVIEW

**Review by jsoltes — CHANGES_REQUESTED** [review]
@pefernan I am missing some kind of reproducer here...

**Comment by mareknovotny** [comment]
@jsoltes it should be in the jira as attachment, please look there

**Comment by jsoltes** [comment]
@mareknovotny this was addressed to @pefernan, I actually meant a unit test reproducing this issue. sorry for confusion :)

**Comment by mareknovotny** [comment]
@jsoltes np, I am watching every issue/PR in payload. So you would like to add new unit test reproducing exactly the issue, right? I was not reading in details the changed tests in the commit, but if that is not enough i get it.

**Comment by jsoltes** [comment]
@mareknovotny yes either the issue or more general scenario... (one of my tasks as a QE is review the prs and ensure the unit coverage is satisfying).

**Review by jsoltes — APPROVED** [review]
As we talked with Pere on bluejeans, it is unfortunately not possible to write the reproducer in code, since the logic is on jsp...

**Comment by mareknovotny** [comment]
ok, so I will merge this PR then

**Pull request merged**
