### PR TITLE
jbpm-form-modeler Zanata-translation-changes 2016.04.11

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by csadilek** [comment]
@mbiarnes there seems to be something wrong here. Why are the i.e. _ru and _zh translations all escaped compared to: https://github.com/droolsjbpm/guvnor/commit/bcbe1677d7f4a7027b9f987f182a2b37d01610af

**Comment by mbiarnes** [comment]
@csadilek spoke to Pere and he told that jbpm-form-modeler needs escaped characters
@pefernan could you look at this PR and in case it s OK give a +1?

**Comment by csadilek** [comment]
@mbiarnes ok, definitely suboptimal, but as this project will be legacy, I guess it doesn't matter. @pefernan can you confirm?

**Comment by pefernan** [comment]
@csadilek yest, that has to be this way. Some special charactares must be scaped to display the form editor literals correctly...

**Pull request merged**
