### PR TITLE
Test for ItemWithThatNameAlreadyExists popup when creating new form.

### PR DESCRIPTION
**Pull request by jsoltes**
This is one selenium test rewritten as an unit test in community. And a small refactoring to make the testing possible.

### CODE REVIEW

**Comment by csadilek** [comment]
@jsoltes thanks! would you mind adding a more descriptive commit message? There's also a typo in the class name: ```NewFormDefinitionlHandler``` should be ```NewFormDefinitionHandler``` which could be fixed in this commit.

@pefernan maybe you can take a quick look as well and "plus one".

**Comment by triceo** [comment]
@csadilek Juraj will be on PTO for a few more days. He'll get to it when he gets back.

**Comment by jsoltes** [comment]
@csadilek I have updated the commit message, as well as fixed the typo...
@pefernan Please, could you take a look at it after the Jenkins build is run?

**Comment by csadilek** [comment]
+1

**Comment by csadilek** [comment]
@jsoltes thanks! We don't plan to keep this project in 7.x. Just in case that affects your plan of moving more tests in here. Of course, it will have to be maintained for the 6.x series.

**Pull request merged**
